//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing
    {
        public int id { get; set; }
        public System.Guid uuid { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public byte status { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public int organization_id { get; set; }
        public int organization_payment_id { get; set; }
    
        public virtual organization_payment organization_payment { get; set; }
        public virtual organization organization { get; set; }
    }
}
