//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cust_order()
        {
            this.order_item = new HashSet<order_item>();
        }
    
        public int id { get; set; }
        public System.Guid uuid { get; set; }
        public byte status { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public int customer_id { get; set; }
        public int customer_payment_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer_payment customer_payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
    }
}
