//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventMagnetEntities : DbContext
    {
        public EventMagnetEntities()
            : base("name=EventMagnetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customer_payment> customer_payment { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<event_venue> event_venue { get; set; }
        public virtual DbSet<newsletter> newsletters { get; set; }
        public virtual DbSet<organization_admin> organization_admin { get; set; }
        public virtual DbSet<organization_payment> organization_payment { get; set; }
        public virtual DbSet<ticket> tickets { get; set; }
        public virtual DbSet<venue> venues { get; set; }
        public virtual DbSet<billing> billings { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<cust_order> cust_order { get; set; }
        public virtual DbSet<organization> organizations { get; set; }
    }
}
