//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @event()
        {
            this.event_venue = new HashSet<event_venue>();
            this.tickets = new HashSet<ticket>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public System.DateTime ticket_sale_start_datetime { get; set; }
        public System.DateTime ticket_sale_end_datetime { get; set; }
        public string descp { get; set; }
        public string keyword { get; set; }
        public string category_name { get; set; }
        public string img_src { get; set; }
        public byte status { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public int organization_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_venue> event_venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
        public virtual organization organization { get; set; }
    }
}
