//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_venue
    {
        public int id { get; set; }
        public System.DateTime book_date { get; set; }
        public byte status { get; set; }
        public int venue_id { get; set; }
        public int event_id { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual venue venue { get; set; }
    }
}
