//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_item
    {
        public int id { get; set; }
        public System.Guid uuid { get; set; }
        public byte status { get; set; }
        public int cust_order_id { get; set; }
        public int ticket_id { get; set; }
    
        public virtual ticket ticket { get; set; }
        public virtual cust_order cust_order { get; set; }
    }
}
