//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventMagnet.modal
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public venue()
        {
            this.event_venue = new HashSet<event_venue>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string descp { get; set; }
        public string address { get; set; }
        public string phone_contact { get; set; }
        public string email_contact { get; set; }
        public string img_src { get; set; }
        public byte status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<event_venue> event_venue { get; set; }
    }
}
